language: php

php:
  - 7.0.25

before_script:
  - cp .env.travis .env
  - mysql -e 'create database chat;'
  - composer self-update
  - composer install --no-interaction

script:
- ./vendor/bin/phpunit